### ISSUE TITLE
Incompatibility with GoProne

### ISSUE THREAD

**Issue by kawaiicakes** [CartoonishVillain/Incapacitated#10]
All relevant details may be found [here.](https://github.com/Alpvax/GoProne/issues/19)

Thanks for your time.

**Comment by Alpvax** [comment]
I do expose the prone state as a capability (on server players and the local client), and there is a markDirty method which you could call to correct the player being prone when no longer incapacitated if you don't mind adding specific compatibility (the method may not have been public in earlier versions). However I am not currently using an interface or exposing an API, so if you don't want to that is fine, players can just press the prone keybind to update after revival.
