### ISSUE TITLE
/incap die crashes game when trying to respawn

### ISSUE THREAD

**Issue by Lambda-Complex** [CartoonishVillain/Incapacitated#11]
Working on a modpack for 1.19.2 (forge 43.2.21) and whenever I used the /incap die command and hit respawn the game crashes to desktop. Unsure if this is a singleplayer only issue as I have yet to try on a server.

[crash-2023-08-11_20.38.41-client.txt](https://github.com/CartoonishVillain/Incapacitated/files/12324604/crash-2023-08-11_20.38.41-client.txt)
[latest.log](https://github.com/CartoonishVillain/Incapacitated/files/12324605/latest.log)

**Comment by CartoonishVillain** [comment]
And this only occurs when /incap die is ran? Or is this any death?

If this is any death, does it happen without the mod?

The amount of mixins in this log that appear unrelated makes me think any death would cause this, at a half-asleep glance

**Comment by Lambda-Complex** [comment]
After removing the mod it still seems to be crashing on respawn. Apologies, it doesn't seem to be incap that's causing the issue.
I'll have to try and decode the crash log to find the actual issue.

[crash-2023-08-11_20.38.41-client.txt](https://github.com/CartoonishVillain/Incapacitated/files/12328325/crash-2023-08-11_20.38.41-client.txt)

**Comment by Lambda-Complex** [comment]
On further investigation it looks like it's an issue with Better Weather conflicting with Oculus + Rubidium.
