### ISSUE TITLE
A suggestion

### ISSUE THREAD

**Issue by GYT0106** [CartoonishVillain/Incapacitated#17]
I think the fallen player should be weak and should not be able to continue to break blocks, place blocks, and attack other mobs (these options can be added in the configuration file to configure the behavior of the fallen player to attack and place and destroy blocks), and at the same time, the player should be so weak that they can't jump after falling (I think this can also add an option in the configuration to prohibit fallen players from jumping), which is beneficial for some special server games to use this mod, I think adding these features is closer to incapacitated, hope for your update

**Comment by CartoonishVillain** [comment]
All of these are features of the latest update. Most of them on by default even. Weakness so strong that it basically prevents attacking has been a thing for a while too. But I may just make that more aggressive.
