### ISSUE TITLE
A bug

### ISSUE THREAD

**Issue by GYT0106** [CartoonishVillain/Incapacitated#18]
If you enable Edible enchant_golden_apple in the configuration file, you can revive it, and if you enable it, there will be a slow effect after falling, although the player can be revived after eating the enchant_golden_apple, the slow effect will not disappear, unless the player really dies, the effect will disappear

**Comment by CartoonishVillain** [comment]
Mod version?
Game version?
Mod loader used?
Version of the mod loader used?
Any configs changed?

**Comment by CartoonishVillain** [comment]
Taking another look and trying to decipher the issue, I figured out what you meant. 

When the slowness effect is enabled on the config, using food to revive the player does not remove the slowness.
