### ISSUE TITLE
Two config files

### ISSUE THREAD

**Issue by ViciousBadger** [CartoonishVillain/Incapacitated#19]
Hi, it seems like the mod creates two config files on install, incapacitated.json and incapacitated.properties.. which one is the "real" config? They seem to have (mostly) the same options.

**Comment by CartoonishVillain** [comment]
Apologies for the inconvenience! 

To answer your question briefly, everything shared between the configs runs off of the JSON system. The only thing we read from properties is lastDownDesaturate, which only takes any effect for client side behavior.

It seems when I migrated this system, I had missed  actually removing the config options we don't read on the fabric side, despite the logic no longer looking at it. Apologies for the inconvenience, and thank you for bringing this to my attention!
