### ISSUE TITLE
[1.20.1 Fabric] Running out of downed time breaks all equipped armor

### ISSUE THREAD

**Issue by DmitriBogdanov** [CartoonishVillain/Incapacitated#22]
# Issue

Getting incapacitated and dying from running out of time causes equipped armor to instantly break.

# Recreating with minimal instance

**Version:**

Minecraft 1.20.1
Fabric 0.16.7 (latest)

**Mods:**

Fabric API 0.92.2 (latest)
Incapacitated 1.7.2LTS (latest)

**Steps:**

1. Create a new world with cheats enabled.
2. Equip a full set of netherite armor.
3. Set gamemode to survival.
4. Die using `/kill`, `/damage @s 200` or any other method.
5. Wait for incapacitated timer to run out.
6. Once the timer runs out there will be a sound of items breaking and the whole set of armor will disappear.

# Notes

- Equiping whole set is not critical - wearing any single armorpiece it still breaks.
- Issue first noticed during testing in a large modpack - disappearing armor caused gravestone mod threads to get stuck due to missing item stacks, which caused tick crash on integrated server, eventually narrowed down to this.
- Setting down time to lower value speeds up testing.

# Full logs

[latest.log](https://github.com/user-attachments/files/17345030/latest.log)

**Comment by CartoonishVillain** [comment]
Hey, thanks for reporting this! I'll have a fix out in the coming week.

**Comment by CartoonishVillain** [comment]
A bit of delay on this patch, I apologize, life suddenly got quite busy. I'll try to get this out as soon as I can.

**Comment by CartoonishVillain** [comment]
This has been addressed in 1.8.2LTS for fabric 1.20.1, and 1.8.2 for the 1.21.1 versions. Thank you again for reporting!
