### ISSUE TITLE
[1.20.1 Fabric] Elytra can be used to fly while incapacitated

### ISSUE THREAD

**Issue by DmitriBogdanov** [CartoonishVillain/Incapacitated#23]
# Issue

Elytra can be used to fly while incapacitated.

# Instance

**Version:**

Minecraft 1.20.1
Fabric 0.16.7 (latest)

**Mods:**

Fabric API 0.92.2 (latest)
Incapacitated 1.7.2LTS (latest)

**Steps:**

1. Create a new world with cheats enabled.
2. Equip an elytra.
3. Set gamemode to survival.
4. Die using `/kill`, `/damage @s 200` or any other method near a ledge.
5. Fall down from the ledge and press spacebar to open elytra.
6. Fly away, in 100 seconds you can cover about 3000 blocks of distance.

# Notes

This is particularly noticeable when using mods [Easy Elytra Takeoff](https://modrinth.com/mod/easy-elytra-takeoff).

Perhaps the use of rockets (or, maybe, even all right-click items) could be blocked while incapacitated.
Or the player can become immovable completely (which would also prevent movement abilities from other mods like, for example, [Spell Engine](https://modrinth.com/mod/spell-engine) from circumventing mobility limitations).
Or perhaps player `FallFlying` NBT could be forced to `0b`, thus preventing any elytra usage.

**Comment by CartoonishVillain** [comment]
Hey, thanks for reporting this!

I will note that I had originally intended for elytras to be usable, however I did not quite account for the Easy Elytra Takeoff which does make it a little too convenient in my opinion.

I'll look into seeing if I can disable it, though I will be putting this change behind a default off config. 

This change can be expected in the coming week. Thank you for reporting!

**Comment by CartoonishVillain** [comment]
This has been addressed in 1.8.2LTS for fabric 1.20.1, and 1.8.2 for the 1.21.1 versions. Thank you again for reporting!

This is addressed in the new "shouldDisableFallFlying" config option. This will not generate in your JSON config file automatically, unless you delete the file in its entirety, or remove it from the config directly. You can alternatively add the value manually to your config to enable it.
