### ISSUE TITLE
Perma re-dying

### ISSUE THREAD

**Issue by Laifsyn** [CartoonishVillain/Incapacitated#3]
So not sure if it was because of that, but I went to spectator mode after being incapacitated. Luckily it was in a test world, I just need to delete my player data and I'm good to start in square 1
![image](https://user-images.githubusercontent.com/99366187/155922695-f9d6475d-173a-4f63-b152-bca5c69308fe.png)
![image](https://user-images.githubusercontent.com/99366187/155922738-8cfc9e6a-79b6-4fe5-a291-fbf684ab8e41.png)

**Comment by Laifsyn** [comment]
Alright, so nope. it wasn't because of Spectator mode. Probably could be Second Chance, but since the idea of Second Chance is to avoid one shots, it shouldn't have triggered with fall dmg

/kill command does kill me but doesn't send me to spawn, but spawns me in the same place instead

**Comment by Laifsyn** [comment]
![image](https://user-images.githubusercontent.com/99366187/155925175-3d2f3040-6ac9-4eaf-80d2-d1aa96dc6382.png)
And the absorption hearts are still there

**Comment by CartoonishVillain** [comment]
I mean, if it **is** an interaction with second chance causing the issue, would seem more like a bug for them given that they would be the ones reviving over zealously. Even then I wasn't able to reproduce this issue, but there is next to no information to work with in this bug. Next time, game version, launcher, mod version, and mod list would all be quite appreciated.
