### ISSUE TITLE
Feature Requests for config: Disable downCounter and change what triggers "giving up"

### ISSUE THREAD

**Issue by SodiumShine** [CartoonishVillain/Incapacitated#5]
I can make this two seperate tickets if you like but:

1. The downCounter only allows for a number above 1, and while I could set it to be a high number, it'll just be surprising for players who suddenly die and not understand why.
2. I've found myself accidentally jumping while down, forgetting that it's what causes me to instantly die. In the heat of combat, it's easy to forget you can't actually jump up some blocks to get away, and so on.

**Comment by CartoonishVillain** [comment]
Not much I can do at the second on the jumping at the second. Unlimited downs I intend to add, with the idea being bleedout doesn't reset, along with the other configurable modifications to the system added.

Now there is an indicator for downs that is configurable. On the latest version, a client side config can desaturate your screen when you have no downs remaining

**Comment by CartoonishVillain** [comment]
I've decided to make giving up a command now in 1.4.3. With that, all features in this request are met.  Closing.
