### ISSUE TITLE
Game crashes when dying

### ISSUE THREAD

**Issue by Givoric** [CartoonishVillain/Incapacitated#7]
Here's crashy's log: https://crashy.net/Gnyfo1fAQG7F349nd4i2
Here's the latest log: https://pastebin.com/gP0GRQr6
The only other mod i have that may impact death as far as i know is "You're in grave danger".

**Comment by CartoonishVillain** [comment]
Unsupported version. I do not plan to fix this bug, but a patch to flag the version will be made (1.19.2 build on 1.19)

**Comment by Givoric** [comment]
alr, ty
